<?php

namespace App\Models;

use App\User;

class Clinic extends User
{
    const ROLE_CLINIC = 1;

    protected $table = 'users';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($model) {
            @unlink(public_path('clinics') . DIRECTORY_SEPARATOR . $model->id);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function profile()
    {
        return $this->hasOne(ClinicProfile::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function certificates()
    {
        return $this->hasMany(ClinicCertificate::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function services()
    {
        return $this->hasMany(ClinicService::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function treatments()
    {
        return $this->hasMany(ClinicTreatment::class, 'clinic_id');
    }

    public function photos()
    {
        return $this->hasMany(ClinicPhoto::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function doctors()
    {
        return $this->hasMany(Doctor::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function languages()
    {
        return $this->hasMany(ClinicLanguage::class, 'clinic_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function payments()
    {
        return $this->hasOne(Payment::class, 'clinic_id');
    }
}
