<?php


namespace App\Models;


use App\User;
use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    const APPROVE = 1;
    const DECLINE = 2;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            // Increase clinic total.
            Clinic::where('id', $model->clinic_id)->update([
                'total_reviews' => Review::where('clinic_id', $model->clinic_id)->count()
            ]);
            // Increase client total.
            User::where('id', $model->client_id)->update([
                'total_reviews' => Review::where('client_id', $model->client_id)->count()
            ]);
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function client()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function clinic()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function appointment()
    {
        return $this->belongsTo(Appointment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function treatment()
    {
        return $this->belongsTo(ClinicTreatment::class);
    }
}
